### ISSUE TITLE
FairlightMixerSourceSetCommand not working

### ISSUE THREAD

**Issue by chriskooken** [LibAtem/LibAtem#16]
I'm having trouble getting the audio channels to mute on the ATEM Mini Extreme. Am I doing something wrong?

`client.SendCommand(new FairlightMixerSourceSetCommand() { MixOption = FairlightAudioMixOption.Off,  Index = AudioSource.Input1 });`

Is there something wrong with this command or is there another command I should use for this?

**Comment by Julusian** [comment]
You will also need to set the [`SourceId`](https://github.com/LibAtem/LibAtem/blob/master/LibAtem/Commands/Audio/Fairlight/FairlightMixerSourceSetCommand.cs#L32) property, as each Input can have multiple Sources. Typically, there is a single 'Stereo' source, but this can be split into a Left and Right.

**Comment by chriskooken** [comment]
Awesome. How do I get the sourceId?

**Comment by Julusian** [comment]
From memory they are some weird values, and as they are a 64bit int I assumed they would not be predictable.
If you listen for https://github.com/LibAtem/LibAtem/blob/master/LibAtem/Commands/Audio/Fairlight/FairlightMixerSourceGetCommand.cs, you will find out the ids for the current sources available for the input. I think the type field will tell you whether it is a mono or stereo source.
Its not very straightforward because of the assumed unpredictability of the ids, and that the available ids can change during use when the input is switched between single stereo or dual mono

**Comment by chriskooken** [comment]
I really appreciate your help so far. When I listen for the `FairlightMixerSourceGetCommand` the only value I seem to get back is -65280. When I send that to the SetCommand, nothing seems to happen.

**Comment by Julusian** [comment]
That number sounds like what I am expecting.

Oh right yeah, you also need to set [Mask](https://github.com/LibAtem/LibAtem/blob/master/LibAtem/Commands/Audio/Fairlight/FairlightMixerSourceSetCommand.cs#L25) so it knows which properties you are setting.

**Comment by chriskooken** [comment]
@Julusian Awesome, that worked thanks!
